[package]
name = "sizef"
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["CordlessCoder"]
description = "A simple #[no_std] crate to format file sizes"
repository = "https://github.com/CordlessCoder/sizef"
